### ISSUE TITLE
doesn't use IE proxy settings in windows / no proxy settings options

### ISSUE THREAD

**Issue by theonlyalterego** [zerkz/HOTSBA#1]
enabling manual proxy settings or having it default to the IE settings; either would be nice.

**Comment by zerkz** [comment]
Definitely within my power. I'll get to work on this for next release.

EDIT: Woops, closed wrong issue.

**Comment by zerkz** [comment]
Fixed!

**Comment by zerkz** [comment]
@theonlyalterego i worked on this a good bit today.. almost done... 100% functional, but having some issues whenever I package the app.

**Comment by zerkz** [comment]
added in v1.0.5! 👍
